const $ = id => document.getElementById(id);
const token = document.querySelector('meta[name="passport-token"]').content;
let initialized = false, pairing = null, busy = false;
async function api(action, data) {
  const response = await fetch('/api/' + action, {method:data === undefined?'GET':'POST',headers:{'X-Passport-Token':token,'Content-Type':'application/json'},body:data === undefined?undefined:JSON.stringify(data)});
  const result = await response.json();
  if (!response.ok) throw new Error(result.error || 'Request failed');
  return result;
}
function notice(message, error=false) { $('notice').textContent=message; $('notice').classList.toggle('error',error); }
function mode() { return document.querySelector('input[name=mode]:checked').value; }
function toggleMode() { $('lan-fields').hidden=mode()!=='lan'; $('ble-fields').hidden=mode()!=='ble'; }
document.querySelectorAll('[name=mode]').forEach(el=>el.addEventListener('change',toggleMode));
function configuration() { const cfg={mode:mode(),host:$('host').value,device:$('device').value,port:Number($('port').value),codex:$('codex').value,autoconnect:$('autoconnect').checked}; if(pairing)cfg.pairing=pairing; return cfg; }
async function operation(work) { if(busy)return;busy=true;try{await work();await refresh();}catch(error){notice(error.message,true);}finally{busy=false;} }
$('pairing').addEventListener('change',async()=>{try{const file=$('pairing').files[0];if(!file)return;if(file.size>65536)throw new Error('Pairing file is too large');const value=JSON.parse(await file.text());if(!/^[0-9a-f]{64}$/i.test(value.key||''))throw new Error('Invalid pairing file');pairing={key:value.key};$('key-state').textContent='Ready to save';notice('Pairing file loaded. Save to keep it on this computer.');}catch(error){pairing=null;notice(error.message,true);}});
async function save(){await api('save',configuration());pairing=null;$('pairing').value='';notice('Settings saved.');}
$('settings').addEventListener('submit',event=>{event.preventDefault();operation(async()=>{await save();await api('connect',{});notice('Connecting… First-time Bluetooth pairing may open an OS prompt.');});});
$('save').onclick=()=>operation(save);
$('disconnect').onclick=()=>operation(async()=>{await api('disconnect',{});notice('Disconnected. Settings are kept for next time.');});
$('test').onclick=()=>operation(async()=>{await api('test',{});notice('Reminder queued. Watch the activity log for confirmation.');});
$('scan').onclick=()=>operation(async()=>{notice('Searching for Bluetooth devices…');$('scan').disabled=true;try{const result=await api('scan',{});$('devices').replaceChildren();for(const device of result.devices){const option=document.createElement('option');option.value=device.address;option.textContent=device.name+' · '+device.address;$('devices').append(option);}$('devices').hidden=!result.devices.length;if(result.devices.length)$('device').value=result.devices[0].address;notice(result.devices.length?'Select your Passport below.':'No Passport found. Check Bluetooth mode and move it closer.');}finally{$('scan').disabled=false;}});
$('devices').onchange=()=>{$('device').value=$('devices').value;};
async function refresh(){const state=await api('status');if(!initialized){for(const id of ['host','device','port','codex'])$(id).value=state.config[id];$('autoconnect').checked=state.config.autoconnect;document.querySelector(`input[name=mode][value="${state.config.mode}"]`).checked=true;toggleMode();initialized=true;}
const active=['starting','connecting','connected','retrying','stopping'].includes(state.status),connected=state.status==='connected';$('badge').textContent=state.status.toUpperCase();$('pet').classList.toggle('awake',connected);$('activity').textContent=connected?(state.running?'Making things happen.':'Ready for the next idea.'):(active?'Finding your companion…':'Taking a little rest.');$('detail').textContent=connected?'Your Passport is receiving live updates.':(active?'Check device mode, IP and any other connected computer.':'Connect to bring your companion online.');$('tasks').textContent=connected?state.running:'—';$('sync').textContent=state.synced_at?new Date(state.synced_at*1000).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'—';$('test').disabled=!connected;$('connect').hidden=active;$('save').hidden=active;$('disconnect').hidden=!active;for(const input of document.querySelectorAll('#settings input, #settings select, #scan'))input.disabled=active;$('key-state').textContent=pairing?'Ready to save':state.key_present?'✓ Key saved locally':'No key saved';$('usage').replaceChildren();for(const key of ['primary','secondary']){const w=state.usage[key];if(!w||!w.duration)continue;const remaining=Math.max(0,Math.min(100,100-w.used));const row=document.createElement('p');const label=document.createElement('span');label.textContent=w.duration>=1440?`${w.duration/1440} days`:`${w.duration/60} hours`;const value=document.createElement('span');value.textContent=`${Math.round(remaining)}% left`;row.append(label,value);const bar=document.createElement('progress');bar.max=100;bar.value=remaining;$('usage').append(row,bar);}$('logs').replaceChildren();for(const entry of state.logs.slice().reverse()){const li=document.createElement('li'),time=document.createElement('time');time.textContent=new Date(entry.at*1000).toLocaleTimeString();li.append(time,document.createTextNode(entry.message));$('logs').append(li);}}
async function poll(){try{await refresh();}catch(error){notice('Console unavailable. Restart the local launcher to reconnect.',true);}setTimeout(poll,2000);}poll();
